import type { Metadata } from "next";
import { Poppins, Playball, Geist } from "next/font/google";
import "./globals.css";
import LenisSmoothScroll from "./providers/lenisProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";


const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500"]
});

const playball = Playball({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" className={cn("font-sans", geist.variable)}
    >
      <body className={`${poppins.className} `}>
        <LenisSmoothScroll/>
        {children}
        <Toaster richColors position="top-right"/>
        </body>
    </html>
  );
}
